version: "3.5"
services:
  delugevpn:
    env_file:
      - ../docker-deluge-openvpn/DockerEnv
    image: delugevpn
    #build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    #network_mode: host
    ports:
      - "8112:8112"
      - "58846:58846"
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/docker/deluge:/config
      - ${ROOT}:/media

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    ports:
      - 9117:9117
    networks:
      - backend

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/TV:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989
    networks:
      - backend

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/Movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 7878:7878
    networks:
      - backend

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/Movies:/movies # movies folder
      - ${ROOT}/TV:/tv # tv shows folder
    ports:
      - 6767:6767
    networks:
      - backend

networks:
  backend:
    driver: bridge
